In [ ]:
  !pip install numpy
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
z= np.array(10)
z.ndim

0

In [ ]:
#one dimension array

In [ ]:
o=np.array([10,12,12,15])
o.ndim

1

In [ ]:
#two dimension array

In [ ]:
t = np.array([[10,10,12,15,14]])
t.ndim

2

In [ ]:
#three dimension array

In [ ]:
th=np.array([[[10,12,14,15,16]]])
th.ndim

3

In [ ]:
# change the data types of the array element

In [ ]:
a= np.array([10,15,52,54])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a= np.array([10,15,52,54], dtype= 'float')
print(a.dtype)
print('hello')
a


float64
hello


array([10., 15., 52., 54.])

In [ ]:
 # other ways of creating an array
1. arange
2.linespace
3. zeros
4. rand
5. randint

In [ ]:
a =np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
b= np.linspace(1,5,15,retstep= 'true')
b

(array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
        2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
        3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ]),
 0.2857142857142857)

In [ ]:
o= np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
r= np.random.rand(5,5)
r

array([[0.41590367, 0.06439405, 0.63566657, 0.20966234, 0.69736734],
       [0.70134523, 0.96276938, 0.51335639, 0.22849764, 0.29641171],
       [0.80121215, 0.02267248, 0.10733381, 0.97156753, 0.41820441],
       [0.84907178, 0.67080179, 0.55030953, 0.70875888, 0.96485848],
       [0.68331607, 0.12206528, 0.428418  , 0.76759429, 0.31670651]])

In [ ]:
r=np.random.randint(5, size = 10)
r

array([1, 1, 0, 1, 1, 4, 2, 1, 0, 0])

Slicing and indexing of arrays

In [ ]:
a= np.array([[1,2,3],[4,5,6]])

In [ ]:
a[1,2]

6

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[0,0]

1

In [ ]:
a[0,1:]

array([2, 3])

In [ ]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
# for 1 and 6
a[[0,1],[0,2]]

array([1, 6])

In [ ]:
# for 3 and 4
a[[0,1],[2,0]]

array([3, 4])

RESHAPING THE ARRAYS




In [ ]:
a= np.random.rand(5,2)

In [ ]:
a

array([[0.47300011, 0.46771514],
       [0.83173239, 0.49632726],
       [0.66680982, 0.37024617],
       [0.0343053 , 0.46951732],
       [0.59795698, 0.43291572]])

In [ ]:
a.reshape(2,5)

array([[0.47300011, 0.46771514, 0.83173239, 0.49632726, 0.66680982],
       [0.37024617, 0.0343053 , 0.46951732, 0.59795698, 0.43291572]])

In [ ]:
a.reshape(10,1)

array([[0.47300011],
       [0.46771514],
       [0.83173239],
       [0.49632726],
       [0.66680982],
       [0.37024617],
       [0.0343053 ],
       [0.46951732],
       [0.59795698],
       [0.43291572]])

In [ ]:
a.reshape(1,10)


array([[0.47300011, 0.46771514, 0.83173239, 0.49632726, 0.66680982,
        0.37024617, 0.0343053 , 0.46951732, 0.59795698, 0.43291572]])

In [ ]:
a.reshape(5,-1)

array([[0.47300011, 0.46771514],
       [0.83173239, 0.49632726],
       [0.66680982, 0.37024617],
       [0.0343053 , 0.46951732],
       [0.59795698, 0.43291572]])

AGGREGATE FUNCTIONS


In [ ]:
a.min()

0.03430529678714711

In [ ]:
a.max()

0.8317323872121672

In [ ]:
a.std()

0.1964296765727333

In [ ]:
a.var()

0.03858461783846861

In [ ]:
a.mean()

0.4840526221998066

STACKING 
stacking used to join 2 diffrent arrays
verticle stacking
horizontal stacking

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

In [ ]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 8])

In [ ]:
np.vstack([a,b])

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])